### PR TITLE
Adding ipv6 support to ltm node and virtual server

### PR DESCRIPTION
**Pull request by papineni87**
Adding v6 node and virtual server in acceptance tests and ran it.

root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip# BIGIP_USER=xxxx BIGIP_PASSWORD=xxxx BIGIP_HOST=xxxxx TF_ACC=1 go test ./bigip -v -run=TestAccBigipLtmNode_create
=== RUN   TestAccBigipLtmNode_create
--- PASS: TestAccBigipLtmNode_create (8.43s)
PASS
ok  	github.com/terraform-providers/terraform-provider-bigip/bigip	8.441s
root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip# 

root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip# BIGIP_USER=xxxx BIGIP_PASSWORD=xxxx BIGIP_HOST=xxxxx TF_ACC=1 go test ./bigip -v -run=TestAccBigipLtmVS_create
=== RUN   TestAccBigipLtmVS_create
--- PASS: TestAccBigipLtmVS_create (9.35s)
=== RUN   TestAccBigipLtmVS_create_Defaultstate
--- PASS: TestAccBigipLtmVS_create_Defaultstate (4.21s)
PASS
ok  	github.com/terraform-providers/terraform-provider-bigip/bigip	13.578s
root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip#

### CODE REVIEW

**Comment by papineni87** [comment]
Ex:

### v6 Node

resource "bigip_ltm_node" "node" {
  name    = "/Common/terraform_node1"
  address = "2001:db8:3c4d::"
}

### V6 pool and virtual server
 
resource "bigip_ltm_pool" "pool" {
  name                = "/Common/test-pool"
  load_balancing_mode = "round-robin"
#  monitors            = ["/Common/terraform_monitor"]
  allow_snat          = "yes"
 allow_nat           = "yes"
}
 
resource "bigip_ltm_virtual_server" "http" {
  name        = "/Common/terraform_vs_http"
  destination = "2002:db8:3c4d::"
  port        = 80
  mask        = "ffff:ffff:ffff::0"
  pool        = "/Common/test-pool"
  depends_on  = [bigip_ltm_pool.pool]
}

### v6 Pool attachment

resource "bigip_ltm_pool" "pool" {
  name                = "/Common/test-pool"
  load_balancing_mode = "round-robin"
#  monitors            = ["/Common/terraform_monitor"]
  allow_snat          = "yes"
  allow_nat           = "yes"
}
 
 
resource "bigip_ltm_pool_attachment" "attach_node1" {
  pool       = "/Common/test-pool"
  node       = "/Common/2001:ed8:77b5:2:10:10:199:42.80"
  depends_on = [bigip_ltm_pool.pool]
}
 
resource "bigip_ltm_pool_attachment" "attach_node2" {
  pool       = "/Common/test-pool"
  node       = "/Common/2001:ed8:77b5:2:10:10:199:43.80"
  depends_on = [bigip_ltm_pool.pool]
}
 
resource "bigip_ltm_virtual_server" "http" {
  pool                       = "/Common/test-pool"
  name                       = "/Common/terraform_vs_http"
  destination                = "2001:ed8:77b5:2:10:10:110:42"
  port                       = 80
  source_address_translation = "automap"
  depends_on                 = [bigip_ltm_pool.pool]
}

**Comment by zx1986** [comment]
nice feature!
but build failed on my Mac ...


```
➜ make build
==> Checking that code complies with gofmt requirements...
go install
# github.com/terraform-providers/terraform-provider-bigip/bigip
bigip/provider.go:130:5: cfg.UserAgent undefined (type *bigip.BigIP has no field or method UserAgent)
bigip/resource_bigip_as3.go:69:25: client.GetTenantList undefined (type *bigip.BigIP has no field or method GetTenantList)
bigip/resource_bigip_as3.go:74:24: client.AddTeemAgent undefined (type *bigip.BigIP has no field or method AddTeemAgent)
bigip/resource_bigip_as3.go:77:34: client.PostAs3Bigip undefined (type *bigip.BigIP has no field or method PostAs3Bigip)
bigip/resource_bigip_as3.go:91:24: client.GetAs3 undefined (type *bigip.BigIP has no field or method GetAs3)
bigip/resource_bigip_as3.go:114:24: client.GetAs3 undefined (type *bigip.BigIP has no field or method GetAs3)
bigip/resource_bigip_as3.go:132:25: client.GetTenantList undefined (type *bigip.BigIP has no field or method GetTenantList)
bigip/resource_bigip_as3.go:139:29: client.TenantDifference undefined (type *bigip.BigIP has no field or method TenantDifference)
bigip/resource_bigip_as3.go:141:18: client.DeleteAs3Bigip undefined (type *bigip.BigIP has no field or method DeleteAs3Bigip)
bigip/resource_bigip_as3.go:151:24: client.AddTeemAgent undefined (type *bigip.BigIP has no field or method AddTeemAgent)
bigip/resource_bigip_as3.go:151:24: too many errors
make: *** [build] Error 2
```

**Comment by RavinderReddyF5** [comment]
@zx1986 
please use: `export GOFLAGS=-mod=vendor` before running `make build` because these vendor bigip changes are available in vendor directory

**Comment by zx1986** [comment]
@RavinderReddyF5 thanks for your info!

**Pull request merged**
